"""Python client for the pmux token engine (Messages + run_stateless)."""

from .client import (
    DEFAULT_CONNECT_TIMEOUT,
    DEFAULT_MAX_FRAME_BYTES,
    DEFAULT_REQUEST_TIMEOUT,
    DEFAULT_RUN_ONCE_TIMEOUT,
    RUN_ONCE_RESPONSE_MARGIN,
    EventItem,
    EventStreamItem,
    EventSubscription,
    PmuxClient,
    PmuxError,
    PmuxFrameTooLargeError,
    PmuxProtocolError,
    PmuxRequestIdMismatchError,
    PmuxSequenceError,
    PmuxServerError,
    PmuxTimeoutError,
    PmuxTransportError,
    PmuxUnexpectedResultError,
    PmuxVersionError,
    ReplayGapItem,
    missing_health_layers,
)
from .messages import (
    PMUX_CONVERSATION_HEADER,
    PMUX_CONVERSATION_HEADER_ALIASES,
    PmuxMessages,
    PmuxMessagesError,
    conversation_header,
    set_conversation_header,
)
from .protocol import (
    MAX_NATIVE_FRAME_BYTES,
    MAX_SAFE_JSON_INTEGER,
    PROTOCOL_VERSION,
    DaemonDiagnosis,
    EffortLevel,
    ErrorBody,
    HealthLayer,
    HealthLayerName,
    LayerFinding,
    PmuxErrorCode,
    RunStatelessRequest,
    StatelessResult,
    StopReason,
    TokenUsage,
    UsageBreakdown,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_MAX_FRAME_BYTES",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_RUN_ONCE_TIMEOUT",
    "MAX_NATIVE_FRAME_BYTES",
    "MAX_SAFE_JSON_INTEGER",
    "PMUX_CONVERSATION_HEADER",
    "PMUX_CONVERSATION_HEADER_ALIASES",
    "PROTOCOL_VERSION",
    "RUN_ONCE_RESPONSE_MARGIN",
    "DaemonDiagnosis",
    "EffortLevel",
    "ErrorBody",
    "EventItem",
    "EventStreamItem",
    "EventSubscription",
    "HealthLayer",
    "HealthLayerName",
    "LayerFinding",
    "PmuxClient",
    "PmuxError",
    "PmuxErrorCode",
    "PmuxFrameTooLargeError",
    "PmuxMessages",
    "PmuxMessagesError",
    "PmuxProtocolError",
    "PmuxRequestIdMismatchError",
    "PmuxSequenceError",
    "PmuxServerError",
    "PmuxTimeoutError",
    "PmuxTransportError",
    "PmuxUnexpectedResultError",
    "PmuxVersionError",
    "ReplayGapItem",
    "RunStatelessRequest",
    "StatelessResult",
    "StopReason",
    "TokenUsage",
    "UsageBreakdown",
    "conversation_header",
    "missing_health_layers",
    "set_conversation_header",
]
