//! Global CLI configuration for `pmux`.
//!
//! Loaded from `~/.config/pseudomux/config.toml` (respects `XDG_CONFIG_HOME`
//! and `PSEUDOMUX_CONFIG` env override). Values are injected as `PMUX_*`
//! environment variables **before** Clap parses, so Clap's native resolution
//! chain applies: CLI flag > env var > config.toml > hardcoded default.
//!
//! Users set this up with `pmux init` or by editing the file directly.

use serde::Deserialize;
use std::path::{Path, PathBuf};

/// Top-level config file schema.
#[derive(Default, Deserialize)]
pub struct PmuxConfig {
    #[serde(default)]
    pub defaults: PmuxDefaults,
}

/// Default values for CLI flags.
#[derive(Default, Deserialize)]
pub struct PmuxDefaults {
    pub model: Option<String>,
    pub permission_mode: Option<String>,
    pub cwd: Option<String>,
    pub agent: Option<String>,
    pub timeout: Option<u64>,
    pub effort: Option<String>,
}

/// Locate the config file. Search order:
/// 1. `PSEUDOMUX_CONFIG` env var
/// 2. `.pseudomux/config.toml` in current directory
/// 3. `$XDG_CONFIG_HOME/pseudomux/config.toml`
/// 4. `~/.config/pseudomux/config.toml`
pub fn config_path() -> Option<PathBuf> {
    if let Ok(explicit) = std::env::var("PSEUDOMUX_CONFIG") {
        let p = PathBuf::from(explicit.trim());
        if p.exists() {
            return Some(p);
        }
    }
    if let Ok(cwd) = std::env::current_dir() {
        let local = cwd.join(".pseudomux").join("config.toml");
        if local.exists() {
            return Some(local);
        }
    }
    if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME") {
        let xdg_path = Path::new(xdg.trim()).join("pseudomux").join("config.toml");
        if xdg_path.exists() {
            return Some(xdg_path);
        }
    }
    if let Some(home) = dirs::home_dir() {
        let user = home.join(".config").join("pseudomux").join("config.toml");
        if user.exists() {
            return Some(user);
        }
    }
    None
}

/// Load the config file (silent no-op if missing).
pub fn load() -> PmuxConfig {
    let Some(path) = config_path() else {
        return PmuxConfig::default();
    };
    let Ok(text) = std::fs::read_to_string(&path) else {
        return PmuxConfig::default();
    };
    toml::from_str(&text).unwrap_or_default()
}

/// Load config and inject as `PMUX_*` environment variables so Clap picks
/// them up via `#[arg(env = "PMUX_*")]`. Only sets a var if it isn't already
/// set — explicit env vars from the user take precedence over the config file.
///
/// Call this in `main()` **before** `Cli::parse()`.
pub fn load_and_apply() {
    let config = load();
    let d = &config.defaults;
    set_if_unset("PMUX_MODEL", d.model.as_deref());
    set_if_unset("PMUX_PERMISSION_MODE", d.permission_mode.as_deref());
    set_if_unset("PMUX_CWD", d.cwd.as_deref());
    set_if_unset("PMUX_AGENT", d.agent.as_deref());
    set_if_unset("PMUX_EFFORT", d.effort.as_deref());
    if let Some(t) = d.timeout {
        set_if_unset("PMUX_TIMEOUT", Some(&t.to_string()));
    }
}

#[allow(unsafe_code)]
fn set_if_unset(key: &str, value: Option<&str>) {
    if let Some(v) = value {
        if std::env::var(key).is_err() {
            // Safe: called in single-threaded main() before any async runtime.
            unsafe { std::env::set_var(key, v) };
        }
    }
}

/// Directory where the config file lives (for `pmux init` to write to).
pub fn config_dir() -> PathBuf {
    if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME") {
        let trimmed = xdg.trim();
        if !trimmed.is_empty() {
            return Path::new(trimmed).join("pseudomux");
        }
    }
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("pseudomux")
}

/// Generate a default config.toml with commented-out fields.
pub fn default_config_text(
    model: &str,
    permission_mode: &str,
    cwd: &str,
    timeout: u64,
    effort: &str,
) -> String {
    format!(
        r#"# pmux configuration — generated by `pmux init`
# CLI flags always override these values.
# Env vars (PMUX_MODEL, PMUX_CWD, etc.) override config but not CLI flags.

[defaults]
model = "{model}"
permission_mode = "{permission_mode}"
cwd = "{cwd}"
agent = "claude-code"
timeout = {timeout}
effort = "{effort}"
"#
    )
}
